### ISSUE TITLE
Fill test data in mysql databases

### ISSUE THREAD

**Issue by kirkovg** [alisakrstova/soa-book-api#5]

**Comment by alisabogat** [comment]
Since we are using a property **sumGrades** in the Rating class for computing the average grade when the user grades a book, I filled this column in the _ratings_ table with the product of the 2 columns we already had (**rating** and **num_ratings**). I then updated the final **rating** column to be the ratio of **sum_grades** and **num_ratings** (to make it precise up to the last decimal place).
SQL query:
`insert into ratings (id, sum_grades, num_ratings, average_grade) select id, (rating * num_ratings), num_ratings, (rating * num_ratings / num_ratings) from books;`

All tables needed for the microservices have data from the _books_ table, except for _users_ which has dummy data.
